# Generated by Django 5.1.2 on 2025-01-06 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_location', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(db_column='latitude', null=True)),
                ('longitude', models.FloatField(db_column='longitude', null=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id_station', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(db_column='capacity', null=True)),
                ('station_code', models.CharField(db_column='station_code', max_length=255, null=True)),
                ('id_location', models.ForeignKey(db_column='id_location', null=True, on_delete=django.db.models.deletion.CASCADE, to='VlibData.location')),
            ],
            options={
                'db_table': 'stations',
            },
        ),
    ]
