services:
  db: 
    image: postgres:latest
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: 12300238
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: .
    ports:
      - '8000:8000'
      - '5432:5432'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://django:12300238@db:5432/django

volumes:
 postgres_data: