services:
  db: 
    image: postgres:latest
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: 12300238
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env

volumes:
 postgres_data: