name: Django CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: vlib
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd="pg_isready -U test_user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    strategy:
      matrix:
        python-version: [ 3.12 ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
  
    - name: Install Dependencies
      working-directory: backend/
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install

    - name: Check environment
      working-directory: backend/
      run: |
        pipenv --venv
        pipenv run pip list
  
    - name: Run Tests
      working-directory: ./backend
      env:
        DJANGO_SETTINGS_MODULE: VlibBackend/settings
        DATABASE_URL: postgres://test_user:test_password@localhost:5432/vlib
      run: |
        # Wait for PostgreSQL to be ready
        until pg_isready -h localhost -U test_user -d test_db; do
          echo "Waiting for PostgreSQL..."
          sleep 1
        done

        pipenv run python manage.py test
