name: Django CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: vlib
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          
        options: >-
          --health-cmd="pg_isready -U test_user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    strategy:
      matrix:
        python-version: [ 3.12 ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
  
    - name: Install Dependencies
      working-directory: backend/
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install

    - name: Check environment
      working-directory: backend/
      run: |
        pipenv --venv
        pipenv run pip list
  
    - name: Wait for PostgreSQL and set up database schema
      run: |
        # Wait for PostgreSQL to be ready
        echo "Waiting for PostgreSQL to be ready..."
        until pg_isready -h localhost -U test_user -d vlib; do
          sleep 1
        done
        echo "PostgreSQL is ready."
        
        # Run the SQL script to set up the database schema
        echo "Setting up the database..."
        psql -h localhost -U test_user -d vlib -f backend/database/script.pgsql

    - name: Run Django tests
      working-directory: backend
      env:
        DJANGO_SETTINGS_MODULE: VlibBackend.settings
        DB_NAME: vlib
        DB_USER: test_user
        DB_PASSWORD: test_password
        DB_HOST: localhost
        DB_PORT: 5432
      run: |
        echo "Running Django tests..."
        pipenv run python manage.py test
